version: '3.8'

networks:
  dev:
    driver: bridge

services:

  backend:
    build:
      context: ./backend
    networks:
      - dev
    expose:
      - 8000
    command: gunicorn --bind 0.0.0.0:8000 bookshop.wsgi

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    ports:
      - "80:80"