# Generated by Django 5.1.7 on 2025-06-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_historyofnotes_date_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='catalog.AuthorsOfBook', to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='sale_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
