# Generated by Django 5.1.7 on 2025-06-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_book_authors'),
        ('catalog', '0008_alter_book_authors_alter_orderhistory_sale_date'),
    ]

    operations = [
    ]
