"""
Django settings for bookshop project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0e2pxfd1-0vv31f(f3uyfze)qxa)s9lpjjv#^3x&-e3eam%r)s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog.apps.CatalogConfig',
    'storages',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Время жизни access-токена
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Время жизни refresh-токена
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'CHECK_REVOKE_TOKEN': True,
    'TOKEN_TYPE_CLAIM': 'token_type',  # Указывает тип токена в payload
    'JTI_CLAIM': 'jti',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'catalog.authentication.CustomJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
AUTHENTICATION_BACKENDS = [
    'catalog.authentication.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',  # Оставляем для админки
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://127.0.0.1:3000',
#     'http://5.129.207.153'
# ]
# CORS_ALLOWED_ORIGINS = [
#     '*'
# ]
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'bookshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bookshop',
        'USER': 'postgres_bookshop',
        'PASSWORD': 'postgres_bookshop',
        'HOST': 'db',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "catalog.User"
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
from dotenv import load_dotenv

load_dotenv() # Загружает переменные из .env

# --- Timeweb Cloud Object Storage Settings (для медиафайлов) ---
# Ключи доступа, полученные в панели Timeweb Cloud
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')

# Имя вашего контейнера (бакета) в Timeweb Cloud Object Storage
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')

# Эндпоинт Timeweb Cloud Object Storage. Это критически важно!
# Обычно это https://s3.timeweb.com для стандартных контейнеров.
# Если вы создавали контейнер в другом регионе, эндпоинт может отличаться (например, для Новосибирска: https://s3.nbl1.timeweb.com).
# Уточните его в документации Timeweb Cloud, если есть сомнения.
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'https://s3.twcstorage.ru')

# Опционально: если вы хотите использовать подпапку в контейнере для медиафайлов
AWS_LOCATION = 'media' # Это означает, что все медиафайлы будут храниться в подпапке 'media/'

# URL для доступа к медиафайлам
MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{AWS_LOCATION}/'

# Определяем, какой класс хранения Django должен использовать по умолчанию для MEDIA_ROOT
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Не перезаписывать файлы с одинаковыми именами, если они уже существуют (по умолчанию False)
AWS_S3_FILE_OVERWRITE = False

# Управление доступом к файлам. 'public-read' делает файлы доступными по URL.
# Если вы не хотите, чтобы файлы были публично доступны, уберите это.
# Важно: это также должно быть настроено в политике CORS контейнера.
AWS_DEFAULT_ACL = 'public-read'

# Отключает генерацию подписанных URL запросов (query string authentication) для публичных файлов.
# Если файлы должны быть доступны всем по прямой ссылке, установите в False.
AWS_QUERYSTRING_AUTH = False

# Отключает проверку SSL-сертификатов (НЕ РЕКОМЕНДУЕТСЯ для продакшена, только если есть проблемы с сертификатами Timeweb)
# AWS_S3_VERIFY_CERTS = False # По умолчанию True, оставьте True, если нет явных проблем

# --- Настройки для локальной разработки vs. продакшн ---
# Рекомендуется использовать переменную окружения USE_S3 для управления этим
# Например, установите USE_S3=True в продакшене и USE_S3=False для локальной разработки
if os.environ.get('USE_S3', 'False') == 'True':
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # Если вы также хотите хранить статические файлы на Timeweb Cloud Object Storage:
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    # STATIC_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/static/'
    # AWS_LOCATION_STATIC = 'static' # Подпапка для статических файлов
else:
    # Для локальной разработки, используйте локальное хранилище
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    # STATIC_URL = '/static/'
    # STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    # STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'