# Generated by Django 5.1.7 on 2025-04-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_authors_historyofnotes_date_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofnotes',
            name='date_note',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
