# Generated by Django 5.1.7 on 2025-04-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_isbn_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='catalog.author'),
        ),
    ]
